[package]
name = "merkle-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.147"
serde_json = "1.0"
hex = "0.4"
ethers-core = "2"
merkle-tree-rs = { git = "https://github.com/lambdaclass/merkle-tree-rs" , branch = "main" }
