apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: "Ethereum RPC"
    type: "yesoreyeram-infinity-datasource"
    typeName: "Infinity"
    uid: "ethereum_rpc"
    access: "proxy"
    url: "${RPC_URL}"
    isDefault: false
    jsonData:
      global_queries: []
    readOnly: false
    editable: true
    basicAuth: false
