{
 "title": "ZK Arcade",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Users Registered",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(users_registered_count{job=\"zk_arcade\"}[$__range]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Failed Proofs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(failed_proofs_count{job=\"zk_arcade\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bumped Proofs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(bumped_proofs_count{job=\"zk_arcade\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Batcher Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "open_batcher_connections{job=\"zk_arcade\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}