# https://hub.docker.com/_/postgres
FROM postgres:16.3

# Environment variables
ENV POSTGRES_USER=zkarcade_user
ENV POSTGRES_PASSWORD=zkarcade_pass
ENV POSTGRES_DB=zkarcade_db

# Expose the default PostgreSQL port
EXPOSE 5432
